UNZIPPED_SCREEN_ADDRESS EQU 58455
LIVE_SCREEN_ADDRESS EQU 16384
CITY_PICTURE_WIDTH_IN_CHARACTERS EQU 10 ; 10 characters
CITY_PICTURE_HEIGHT_IN_CHARACTERS EQU 12 ; 12 characters
CITY_PICTURE_WIDTH_IN_PIXELS EQU CITY_PICTURE_WIDTH_IN_CHARACTERS*8 ; 80
CITY_PICTURE_HEIGHT_IN_PIXELS EQU CITY_PICTURE_HEIGHT_IN_CHARACTERS*8 ; 96
CITY_PICTURE_HORIZONTAL_OFFSET_IN_PIXELS EQU (256-CITY_PICTURE_WIDTH_IN_PIXELS) ; 176
CITY_PICTURE_HORIZONTAL_OFFSET_IN_CHARACTERS EQU (32-CITY_PICTURE_WIDTH_IN_CHARACTERS) ; 32-10 = 22

;; A: Y Characters shift down
;; C: X Characters shift left
load_screen:
ld b,0

LD HL, UNZIPPED_SCREEN_ADDRESS
LD DE, LIVE_SCREEN_ADDRESS
add de, bc

LD A, CITY_PICTURE_HEIGHT_IN_PIXELS
LD BC, CITY_PICTURE_WIDTH_IN_CHARACTERS
load_screen_loop:
LDIR
; LDIR = Repetir LDI hasta que BC valga 0
;     = Repetir:
;          Copiar [HL] en [DE]
;          DE=DE+1
;          HL=HL+1
;          BC=BC-1
;       Hasta que BC = 0

LD BC, CITY_PICTURE_HORIZONTAL_OFFSET_IN_CHARACTERS
ADD HL, BC
EX DE, HL
ADD HL, BC
EX DE, HL
LD BC, CITY_PICTURE_WIDTH_IN_CHARACTERS
DEC A
OR A

JR NZ, load_screen_loop
paraaa:
jr paraaa
ret